services:
  database:
    image: 'postgres:latest'
    ports:
      - 54321:5432
    environment:
      - POSTGRES_PASSWORD=ridilocal
    volumes:
      - postgres-data:/var/lib/postgresql/data/
  
volumes:
  postgres-data: {}
