// Code generated by sqlc. DO NOT EDIT.

import { Sql } from "postgres";

export const sendMessageQuery = `-- name: SendMessage :exec
SELECT  from pgmq.send(
  queue_name => $1::text,
  msg        => $2::jsonb
)`;

export interface SendMessageArgs {
    queueName: string;
    message: any;
}

export async function sendMessage(sql: Sql, args: SendMessageArgs): Promise<void> {
    await sql.unsafe(sendMessageQuery, [args.queueName, args.message]);
}

export const pollMessagesQuery = `-- name: PollMessages :many
SELECT
    msg_id::integer,
    read_ct::integer,
    enqueued_at::timestamp,
    vt::timestamp as visibility_timeout,
    message:: jsonb
FROM pgmq.read(
  queue_name => $1::text,
  vt         => $2::integer,
  qty        => $3::integer
)`;

export interface PollMessagesArgs {
    queueName: string;
    visibilityTimeoutSeconds: number;
    qty: number;
}

export interface PollMessagesRow {
    msgId: number;
    readCt: number;
    enqueuedAt: Date;
    visibilityTimeout: Date;
    message: any;
}

export async function pollMessages(sql: Sql, args: PollMessagesArgs): Promise<PollMessagesRow[]> {
    return (await sql.unsafe(pollMessagesQuery, [args.queueName, args.visibilityTimeoutSeconds, args.qty]).values()).map(row => ({
        msgId: row[0],
        readCt: row[1],
        enqueuedAt: row[2],
        visibilityTimeout: row[3],
        message: row[4]
    }));
}

export const archiveMessageQuery = `-- name: ArchiveMessage :exec
SELECT pgmq.archive(
  queue_name => $1::text,
  msg_id     => $2::integer
)`;

export interface ArchiveMessageArgs {
    queueName: string;
    messageId: number;
}

export interface ArchiveMessageRow {
    archive: string | null;
}

export async function archiveMessage(sql: Sql, args: ArchiveMessageArgs): Promise<void> {
    await sql.unsafe(archiveMessageQuery, [args.queueName, args.messageId]);
}

export const archiveMessagesQuery = `-- name: ArchiveMessages :exec
SELECT pgmq.archive(
  queue_name => $1::text,
  msg_ids    => $2::integer[]
)`;

export interface ArchiveMessagesArgs {
    queueName: string;
    messageIds: number[];
}

export interface ArchiveMessagesRow {
    archive: string | null;
}

export async function archiveMessages(sql: Sql, args: ArchiveMessagesArgs): Promise<void> {
    await sql.unsafe(archiveMessagesQuery, [args.queueName, args.messageIds]);
}

export const deleteMessageQuery = `-- name: DeleteMessage :exec
SELECT pgmq.delete(
  queue_name => $1::text,
  msg_id     => $2::integer
)`;

export interface DeleteMessageArgs {
    queueName: string;
    messageId: number;
}

export interface DeleteMessageRow {
    delete: string | null;
}

export async function deleteMessage(sql: Sql, args: DeleteMessageArgs): Promise<void> {
    await sql.unsafe(deleteMessageQuery, [args.queueName, args.messageId]);
}

export const deleteMessagesQuery = `-- name: DeleteMessages :exec
SELECT pgmq.delete(
  queue_name => $1::text,
  msg_ids    => $2::integer[]
)`;

export interface DeleteMessagesArgs {
    queueName: string;
    messageId: number[];
}

export interface DeleteMessagesRow {
    delete: string | null;
}

export async function deleteMessages(sql: Sql, args: DeleteMessagesArgs): Promise<void> {
    await sql.unsafe(deleteMessagesQuery, [args.queueName, args.messageId]);
}

