// Code generated by sqlc. DO NOT EDIT.

import { Sql } from "postgres";

export const routesGetQuery = `-- name: RoutesGet :many
with points_array as (
	select 
		id, 
		array_agg(array[postgis.st_y(p.geom), postgis.st_x(p.geom)] order by p.path) as lat_lon_array
	from routes r, postgis.st_dumppoints(r.linestring) p
	where r.user_id = $1
		and r.id = $2
	group by r.id
) 
select 
	r.id,
	r.name,
	r.created_at,
	pa.lat_lon_array,
	p.id as plan_id,
	p.name as plan_name,
	p.state as plan_state
from routes r
inner join plans p
	on p.id = r.plan_id
inner join points_array pa
	on pa.id = r.id
where r.user_id = $1
	and r.id = $2
order by 
	r.created_at desc`;

export interface RoutesGetArgs {
    userId: string;
    id: string;
}

export interface RoutesGetRow {
    id: string;
    name: string;
    createdAt: Date;
    latLonArray: string[];
    planId: string;
    planName: string;
    planState: "new" | "planning" | "done" | "error";
}

export async function routesGet(sql: Sql, args: RoutesGetArgs): Promise<RoutesGetRow[]> {
    return (await sql.unsafe(routesGetQuery, [args.userId, args.id]).values()).map(row => ({
        id: row[0],
        name: row[1],
        createdAt: row[2],
        latLonArray: row[3],
        planId: row[4],
        planName: row[5],
        planState: row[6]
    }));
}

export const planListQuery = `-- name: PlanList :many
select 
	p.id,
	p.name,
	p.from_lat,
	p.from_lon,
	p.to_lat,
	p.to_lon,
	p.state,
	p.created_at,
	r.id as route_id,
	r.name as route_name,
	r.created_at as route_created_at
from plans p
left join routes r 
	on r.plan_id = p.id
where p.user_id = $1
order by
	p.created_at desc`;

export interface PlanListArgs {
    userId: string;
}

export interface PlanListRow {
    id: string;
    name: string;
    fromLat: string;
    fromLon: string;
    toLat: string;
    toLon: string;
    state: "new" | "planning" | "done" | "error";
    createdAt: Date;
    routeId: string | null;
    routeName: string | null;
    routeCreatedAt: Date | null;
}

export async function planList(sql: Sql, args: PlanListArgs): Promise<PlanListRow[]> {
    return (await sql.unsafe(planListQuery, [args.userId]).values()).map(row => ({
        id: row[0],
        name: row[1],
        fromLat: row[2],
        fromLon: row[3],
        toLat: row[4],
        toLon: row[5],
        state: row[6],
        createdAt: row[7],
        routeId: row[8],
        routeName: row[9],
        routeCreatedAt: row[10]
    }));
}

export const planCreateQuery = `-- name: PlanCreate :one
insert into plans (user_id, id, name, from_lat, from_lon, to_lat, to_lon)
values ($1, $2, $3, $4, $5, $6, $7)
returning id`;

export interface PlanCreateArgs {
    userId: string;
    id: string;
    name: string;
    fromLat: string;
    fromLon: string;
    toLat: string;
    toLon: string;
}

export interface PlanCreateRow {
    id: string;
}

export async function planCreate(sql: Sql, args: PlanCreateArgs): Promise<PlanCreateRow | null> {
    const rows = await sql.unsafe(planCreateQuery, [args.userId, args.id, args.name, args.fromLat, args.fromLon, args.toLat, args.toLon]).values();
    if (rows.length !== 1) {
        return null;
    }
    const row = rows[0];
    if (!row) {
        return null;
    }
    return {
        id: row[0]
    };
}

