name: map-data-handler
services:
  map_data_handler:
    extends:
      file: ./docker-compose-base.yaml
      service: deno-service
    command: ./startup.sh ./map-data-handler/main.ts
    environment:
      SUPABASE_DB_URL: ${SUPABASE_DB_URL}
      RIDI_ENV_NAME: map-data-handler
