services:
  deno_service:
    restart: on-failure
    build:
      args:
        RIDI_ROUTER_VERSION: v0.6.12
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ${RIDI_DATA_DIR}:/ridi-data
    environment:
      RIDI_DATA_DIR: ${RIDI_DATA_DIR}
      PORT: 2727
    healthcheck:
      test: curl --fail http://localhost:2727 || exit 1
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 5s
