FROM node:23-alpine as build

WORKDIR /app

ARG RIDI_ROUTER_VERSION

RUN curl -L "https://github.com/tomsjansons/ridi-router/releases/download/${RIDI_ROUTER_VERSION}/ridi-router-linux-amd64.zip" -o ridi-router-linux-amd64.zip \
		&& unzip ridi-router-linux-amd64.zip \
		&& mv ridi-router-linux-amd64 ridi-router \
    && chmod +x ridi-router

COPY . .
RUN pnpm install

RUN chmod +x startup.sh

RUN pnpm run tsc

CMD ["node", "./src/index.ts"]
