name: router-handler
services:
  router_handler:
    extends:
      file: ./docker-compose-base.yaml
      service: deno_service
    volumes:
      - /var/log/ridi-service:/var/log/ridi-service-router
    command: ./startup.sh ./router-handler/main.ts
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SECRET_KEY: ${SUPABASE_SECRET_KEY}
      RIDI_ENV_NAME: router-handler
