receivers:
  filelog/deploy:
    directory: /var/log/ridi-service-deploy
  filelog/map-data:
    directory: /var/log/ridi-service-map-data
  filelog/router:
    directory: /var/log/ridi-service-router
  hostmetrics:
    root_path: /
    collection_interval: 5s
    scrapers:
      load:
      memory:
  docker_stats:
    collection_interval: 5s
    api_version: '1.45'
    metrics:
      container.cpu.utilization:
        enabled: true
      container.blockio.io_service_bytes_recursive:
        enabled: false
      container.cpu.usage.kernelmode:
        enabled: false
      container.cpu.usage.total:
        enabled: false
      container.cpu.usage.usermode:
        enabled: false
      container.memory.file:
        enabled: false
      container.memory.percent:
        enabled: false
      container.memory.total_cache:
        enabled: false
      container.memory.usage.limit:
        enabled: false
      container.network.io.usage.rx_bytes:
        enabled: false
      container.network.io.usage.rx_dropped:
        enabled: false
      container.network.io.usage.tx_bytes:
        enabled: false
      container.network.io.usage.tx_dropped:
        enabled: false
processors:
  resourcedetection/system:
    detectors: ["system"]
    system:
      hostname_sources: ["os"]
  memory_limiter:
    check_interval: 1s
    limit_percentage: 75
    spike_limit_percentage: 15
  batch:
    send_batch_size: 10000
    timeout: 10s

extensions:
  zpages: {}

exporters:
  otlphttp/openobserve:
    endpoint: https://api.openobserve.ai/api/toms_organization_50898_KmgBoq7eiBvgqoe/
    headers:
      Authorization: "Basic dG9tcy5qYW5zb25zQGhvb2Qtc29mdHdhcmUubHY6RDUxNjJrZm4zOEVvcUE0MHQ3Wjk="
  otlphttp/openobserve_ridi-service:
    endpoint: https://api.openobserve.ai/api/toms_organization_50898_KmgBoq7eiBvgqoe/
    headers:
      Authorization: "Basic dG9tcy5qYW5zb25zQGhvb2Qtc29mdHdhcmUubHY6RDUxNjJrZm4zOEVvcUE0MHQ3Wjk="
      stream-name: ridi-service

service:
  extensions: [zpages]
  pipelines:
    metrics:
      receivers: [hostmetrics, docker_stats]
      processors: [resourcedetection/system, memory_limiter, batch]
      exporters: [otlphttp/openobserve]
    logs:
      receivers: [filelog/deploy, filelog/router, filelog/map-data]
      processors: [resourcedetection/system, memory_limiter, batch]
      exporters: [otlphttp/openobserve_ridi-service]
