receivers:
  otlp:
    protocols:
      grpc:
      http:
  filelog/std:
    include: [ /var/log/ridi-service-deploy/service.log, /var/log/ridi-service-map-data/service.log, /var/log/ridi-service-router/service.log ]
  hostmetrics:
    root_path: /
    collection_interval: 5s
    scrapers:
      load:
      memory:
  docker_stats:
    collection_interval: 5s
    api_version: '1.45'
    metrics:
      container.cpu.utilization:
        enabled: true
      container.blockio.io_service_bytes_recursive:
        enabled: false
      container.cpu.usage.kernelmode:
        enabled: false
      container.cpu.usage.total:
        enabled: false
      container.cpu.usage.usermode:
        enabled: false
      container.memory.file:
        enabled: false
      container.memory.percent:
        enabled: false
      container.memory.total_cache:
        enabled: false
      container.memory.usage.limit:
        enabled: false
      container.network.io.usage.rx_bytes:
        enabled: false
      container.network.io.usage.rx_dropped:
        enabled: false
      container.network.io.usage.tx_bytes:
        enabled: false
      container.network.io.usage.tx_dropped:
        enabled: false
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 30s
          static_configs:
            - targets: ['localhost:8888']
processors:
  resourcedetection/system:
    detectors: ["system"]
    system:
      hostname_sources: ["os"]
  memory_limiter:
    check_interval: 1s
    limit_percentage: 75
    spike_limit_percentage: 15
  batch:
    send_batch_size: 10000
    timeout: 10s
  attributes/betterstack:
    actions:
      - key: better_stack_source_token
        value: =====================================================
        action: insert

extensions:
  zpages: {}

exporters:
  otlphttp/openobserve:
    endpoint: https://api.openobserve.ai/api/toms_organization_50898_KmgBoq7eiBvgqoe/
    headers:
      Authorization: "Basic ==============================================="
  otlphttp/openobserve_ridi-service:
    endpoint: https://api.openobserve.ai/api/toms_organization_50898_KmgBoq7eiBvgqoe/
    headers:
      Authorization: "Basic =============================================="
      stream-name: ridi-service
  otlp/betterstack:
    endpoint: "https://in-otel.logs.betterstack.com:443"
  prometheusremotewrite/betterstack:
    endpoint: "https://in-otel.logs.betterstack.com/metrics"

service:
  extensions: [zpages]
  pipelines:
    metrics:
      receivers: [hostmetrics, docker_stats]
      processors: [resourcedetection/system, memory_limiter, batch]
      exporters: [otlphttp/openobserve]
    logs:
      receivers: [filelog/std]
      processors: [resourcedetection/system, memory_limiter, batch]
      exporters: [otlphttp/openobserve_ridi-service]
    metrics/betterstack:
      receivers: [hostmetrics, docker_stats, otlp, prometheus] # You can add more metrics receivers here
      processors: [batch, attributes/betterstack]
      exporters: [prometheusremotewrite/betterstack]
    logs/betterstack:
      receivers: [filelog/std, otlp, filelog/betterstack] # You can add more logs receivers here
      processors: [batch, attributes/betterstack]
      exporters: [otlp/betterstack]
