name: deploy-handler
services:
  deploy_handler:
    extends:
      file: ./docker-compose-base.yaml
      service: deno_service
    volumes:
      - /var/log/ridi-service-deploy:/var/log/ridi-service
    command: ./startup.sh ./deploy-handler/main.ts
    environment:
      COOLIFY_API_URL: ${COOLIFY_API_URL}
      COOLIFY_TOKEN: ${COOLIFY_TOKEN}
      COOLIFY_DEPLOYMENT_ID_ROUTER_HANDLER: ${COOLIFY_DEPLOYMENT_ID_ROUTER_HANDLER}
      COOLIFY_DEPLOYMENT_ID_MAP_DATA_HANDLER: ${COOLIFY_DEPLOYMENT_ID_MAP_DATA_HANDLER}
      RIDI_ENV_NAME: deploy-handler
