name: router-handler
services:
  router-handler:
    extends:
      file: ../deno-base-docker-compose.yaml
      service: deno-service
    command: deno run -A --unstable-ffi ./router-handler/main.ts
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SECRET_KEY=${SUPABASE_SECRET_KEY}
