// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	SUPABASE_URL: "http://127.0.0.1:54321";
	SUPABASE_DB_URL: string;
	SUPABASE_SERVICE_ROLE_KEY: string;
}
