// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	SUPABASE_URL: string;
	SUPABASE_DB_URL: string;
	RIDI_APP_URL: string;
	SUPABASE_SERVICE_ROLE_KEY: string;
	STRIPE_SECRET_KEY: string;
	STRIPE_PRICE_ID_MONTLY: string;
	STRIPE_PRICE_ID_YEARLY: string;
	STRIPE_WEBHOOK_SECRET: string;
}
