name = "ridi-apps-api"
main = "src/index.ts"
compatibility_date = "2025-01-29"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true

[observability]
enabled = true

# Environment Variables
# https://developers.cloudflare.com/workers/wrangler/configuration/#environment-variables
[vars]
SUPABASE_URL = "https://sb.ridi.bike"
RIDI_APP_URL = "https://app.ridi.bike"
SENTRY_DSN = "https://57ef996c2cdb0754386a7cfa02783c4f@o337283.ingest.us.sentry.io/4509016159420416"
RIDI_ENV = "prod"

# Note: Use secrets to store sensitive data.
# https://developers.cloudflare.com/workers/configuration/secrets/

# Static Assets
# https://developers.cloudflare.com/workers/static-assets/binding/
# [assets]
# directory = "./public/"
# binding = "ASSETS"

# Service Bindings (communicate between multiple Workers)
# https://developers.cloudflare.com/workers/wrangler/configuration/#service-bindings
# [[services]]
# binding = "MY_SERVICE"
# service = "my-service"
