name: deploy-handler
services:
  deploy-handler:
    extends:
      file: ../deno-base-docker-compose.yaml
      service: deno-service
    command: deno run -A --unstable-ffi ./deploy-handler/main.ts
    environment:
      - COOLIFY_API_URL:${COOLIFY_API_URL}
      - COOLIFY_TOKEN:${COOLIFY_TOKEN}
      - COOLIFY_DEPLOYMENT_ID_ROUTER_HANDLER:${COOLIFY_DEPLOYMENT_ID_ROUTER_HANDLER}
      - COOLIFY_DEPLOYMENT_ID_MAP_DATA_HANDLER:${COOLIFY_DEPLOYMENT_ID_MAP_DATA_HANDLER}
