name: deploy-handler
services:
  deploy-handler:
    extends:
      file: ../deno-base-docker-compose.yaml
      service: deno-service
    build:
      context: .
      dockerfile: ../Dockerfile
    environment:
      - COOLIFY_API_URL:${COOLIFY_API_URL}
      - COOLIFY_TOKEN:${COOLIFY_TOKEN}
      - COOLIFY_DEPLOYMENT_ID_ROUTER_HANDLER:${COOLIFY_DEPLOYMENT_ID_ROUTER_HANDLER}
      - COOLIFY_DEPLOYMENT_ID_MAP_DATA_HANDLER:${COOLIFY_DEPLOYMENT_ID_MAP_DATA_HANDLER}
